// Auto-generated by Mimi F9 Python binding generator.
// Requires: pybind11, Mimi C header + runtime library.
// Build: see accompanying CMakeLists.txt

#ifndef MIMI_PY_BIND_MATH_H
#define MIMI_PY_BIND_MATH_H

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <cstdint>
#include <cstddef>
extern "C" {
#include "mimi_ffi.h"
}
namespace py = pybind11;

// Mimi C API types — defined in mimi_ffi.h as typedefs
// Ensure C++ compatibility:
using MimiHandle = int64_t;
using MimiCap = int64_t;

PYBIND11_MODULE(math, m) {
    m.doc() = "Mimi language FFI bindings (auto-generated)";

    // add — add
    m.def("add", [](int64_t a, int64_t b) -> int64_t {
        return add(a, b);
    }, "add"
    );

    // sub — sub
    m.def("sub", [](int64_t a, int64_t b) -> int64_t {
        return sub(a, b);
    }, "sub"
    );

    // mul — mul
    m.def("mul", [](int64_t a, int64_t b) -> int64_t {
        return mul(a, b);
    }, "mul"
    );

    // fact — fact
    m.def("fact", [](int64_t n) -> int64_t {
        return fact(n);
    }, "fact"
    );

}

#endif // MIMI_PY_BIND_MATH_H
