// Auto-generated by Mimi F9 Python binding generator.
// Requires: pybind11, Mimi C header + runtime library.
// Build: see accompanying CMakeLists.txt

#ifndef MIMI_PY_BIND_CONTRACTS_SIMPLE_H
#define MIMI_PY_BIND_CONTRACTS_SIMPLE_H

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <cstdint>
#include <cstddef>
extern "C" {
#include "mimi_ffi.h"
}
namespace py = pybind11;

// Mimi C API types — defined in mimi_ffi.h as typedefs
// Ensure C++ compatibility:
using MimiHandle = int64_t;
using MimiCap = int64_t;

PYBIND11_MODULE(contracts_simple, m) {
    m.doc() = "Mimi language FFI bindings (auto-generated)";

    // factorial — factorial
    m.def("factorial", [](int64_t n) -> int64_t {
        return factorial(n);
    }, "factorial"
    );

    // divide_safe — divide_safe
    m.def("divide_safe", [](int64_t a, int64_t b) -> int64_t {
        return divide_safe(a, b);
    }, "divide_safe"
    );

}

#endif // MIMI_PY_BIND_CONTRACTS_SIMPLE_H
