// Auto-generated by Mimi F9 Python binding generator.
// Requires: pybind11, Mimi C header + runtime library.
// Build: see accompanying CMakeLists.txt

#ifndef MIMI_PY_BIND_STRUTIL_H
#define MIMI_PY_BIND_STRUTIL_H

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <cstdint>
#include <cstddef>
extern "C" {
#include "mimi_ffi.h"
}
namespace py = pybind11;

// Mimi C API types — defined in mimi_ffi.h as typedefs
// Ensure C++ compatibility:
using MimiHandle = int64_t;
using MimiCap = int64_t;

PYBIND11_MODULE(strutil, m) {
    m.doc() = "Mimi language FFI bindings (auto-generated)";

    // c_reverse — c_reverse
    m.def("c_reverse", [](int64_t n) -> int64_t {
        return c_reverse(n);
    }, "c_reverse"
    );

    // c_count_digits — c_count_digits
    m.def("c_count_digits", [](int64_t n) -> int64_t {
        return c_count_digits(n);
    }, "c_count_digits"
    );

    // c_is_palindrome — c_is_palindrome
    m.def("c_is_palindrome", [](int64_t n) -> int64_t {
        return c_is_palindrome(n);
    }, "c_is_palindrome"
    );

    // c_gcd — c_gcd
    m.def("c_gcd", [](int64_t a, int64_t b) -> int64_t {
        return c_gcd(a, b);
    }, "c_gcd"
    );

    // reverse — reverse
    m.def("reverse", [](int64_t n) -> int64_t {
        return reverse(n);
    }, "reverse"
    );

    // count_digits — count_digits
    m.def("count_digits", [](int64_t n) -> int64_t {
        return count_digits(n);
    }, "count_digits"
    );

    // is_palindrome — is_palindrome
    m.def("is_palindrome", [](int64_t n) -> int64_t {
        return is_palindrome(n);
    }, "is_palindrome"
    );

    // gcd — gcd
    m.def("gcd", [](int64_t a, int64_t b) -> int64_t {
        return gcd(a, b);
    }, "gcd"
    );

}

#endif // MIMI_PY_BIND_STRUTIL_H
