// Auto-generated by Mimi F9 Python binding generator.
// Requires: pybind11, Mimi C header + runtime library.
// Build: see accompanying CMakeLists.txt

#ifndef MIMI_PY_BIND_RUST_FUNCTIONS_H
#define MIMI_PY_BIND_RUST_FUNCTIONS_H

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <cstdint>
#include <cstddef>
extern "C" {
#include "mimi_ffi.h"
}
namespace py = pybind11;

// Mimi C API types — defined in mimi_ffi.h as typedefs
// Ensure C++ compatibility:
using MimiHandle = int64_t;
using MimiCap = int64_t;

PYBIND11_MODULE(rust_functions, m) {
    m.doc() = "Mimi language FFI bindings (auto-generated)";

    // rust_fib — rust_fib
    m.def("rust_fib", [](int64_t n) -> int64_t {
        return rust_fib(n);
    }, "rust_fib"
    );

    // rust_sum_squares — rust_sum_squares
    m.def("rust_sum_squares", [](int64_t n) -> int64_t {
        return rust_sum_squares(n);
    }, "rust_sum_squares"
    );

    // mimi_fib — mimi_fib
    m.def("mimi_fib", [](int64_t n) -> int64_t {
        return mimi_fib(n);
    }, "mimi_fib"
    );

    // mimi_sum_squares — mimi_sum_squares
    m.def("mimi_sum_squares", [](int64_t n) -> int64_t {
        return mimi_sum_squares(n);
    }, "mimi_sum_squares"
    );

}

#endif // MIMI_PY_BIND_RUST_FUNCTIONS_H
